# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ebc8008369196e8dfa35b56a897b9f21a072cf9283fcc9778749bac817d9b5934723054702045442d842e8674e589d10aab76f8d3113ff55e77d7503fa233be

test:
  secret_key_base: 543474afbe317540319d2bf42671b54335a376ef9b874ee34e1ebfe885992cf67c7064f202ea4bdd29d19a61d25f2d6e6d7da6bf29b06eee2b5b74d4e19bc3ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
